#Parameters specific to the NGRIP ice core
calc_thinning: True
thickness: 3085. #NorthGrip members, Nature, 2004.
iedepth_top: 3.5 #Value calculated with an average density of 0.44 for the first 8 m.
pprime: 1.
sliding: 0.
muprime: -2.4
k: 0.5

calc_deporate: True
calc_deporate_method: 'd18O'
deporate0: 0.20
beta: 0.019
deporate_prior_sigma: 0.5

calc_lid: True
lid_value: 90.
lid_prior_sigma: 0.3

age_top_prior: -28. #age at the top of the sequence
age_top_sigma: 1. #Error on top age
depth_grid: #depth grid for the age calculation
    type: 'regular'
    start: &depth_start 8.
    end: &depth_end 3085.
    resolution: 1.
age_truncation:
    inf: ~
    sup: 130000.
    
corr_deporate_grid: #Age grid for the deporate correction function
    type: 'linear' #regular or linear
    start: -28.
    end:  124972.
    nb_steps: 2500 
    ratio: 0.2 #Ratio of the first step size to the average step size
corr_lid_grid: #Age grid for the LID correction function
    type: 'regular'
    start: -1028.
    end:  124972.
    nb_steps: 131 
    ratio: 0.2 #Ratio of the first step size to the average step size